### ISSUE TITLE
version key

### ISSUE THREAD

**Issue by dborsnich** [tikismoke/home-assistant-plcbus#7]
Hi Tiki!

Please, Can you check this error please, Thanks!!!

2021-05-24 18:55:02 ERROR (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'plcbus'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'plcbus'

**Comment by tikismoke** [comment]
For sure.
It will not be too difficult 😉

**Comment by dborsnich** [comment]
Thanks!
It's strange. I tested with 2 differents Raspberry Pi4 and works for a while an then fails.
When I restart the logs says:

2021-05-25 10:49:56 WARNING (MainThread) [homeassistant.components.switch] SwitchDevice is deprecated, modify PlcbusSwitch to extend SwitchEntity
2021-05-25 10:50:02 ERROR (MainThread) [homeassistant.components.switch] Platform plcbus does not generate unique IDs. ID PlcbusSwitch_D1_A1 already exists - ignoring switch.plcbusswitch_d1_a1
2021-05-25 10:50:02 ERROR (MainThread) [homeassistant.components.switch] Platform plcbus does not generate unique IDs. ID PlcbusSwitch_D1_A2 already exists - ignoring switch.plcbusswitch_d1_a2
2021-05-25 10:50:02 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook ae575c2b436ec7ac727c43318da76b54128917a5b5b08e18b2ee8ed7362abeb1 from 192.168.11.23
2021-05-25 10:50:16 ERROR (Thread-3) [root] Uncaught thread exception
Traceback (most recent call last):
File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
self.run()
File "/config/custom_components/plcbus/lib/PLCBusSerialHandler.py", line 270, in run
self.receive()
File "/config/custom_components/plcbus/lib/PLCBusSerialHandler.py", line 240, in receive
self._cb(self.explicit_message(m_string.decode('utf-8')))
File "/config/custom_components/plcbus/switch.py", line 68, in commandCB
ToggleEntity.async_write_ha_state(entity)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 288, in async_write_ha_state
raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <Entity PlcbusSwitch_D1_A2: on>

I will do a test in a PC with proxmox softwate

Thanks!

**Comment by tikismoke** [comment]
It happens to me also and I need to either unplug/replug the USB adaptor or restart the vm (or host if not virtual)

**Comment by dborsnich** [comment]
ok, Thanks!!!

**Comment by tikismoke** [comment]
I need to check this:
[homeassistant.components.switch]` SwitchDevice is deprecated, modify PlcbusSwitch to extend SwitchEntity`


Should not appears since:

https://github.com/tikismoke/home-assistant-plcbus/issues/5

**Comment by dborsnich** [comment]
I put the version 0.0.2 in the manifest and change the SwitchDevice for SwitchEntity in switch.py. 
I found the information #5, but in the switch.py follow appearing in the same lines SwitchDevice

Thanks

**Comment by dborsnich** [comment]
if I remeber well, You dont have dimmer and curtains plcbus modules, no?
I could send you if you need some of them. Here I use one dimmer with switch config and works, but obviusly, dont dimmer
Thanks!

**Comment by tikismoke** [comment]
It could be cool and allow more dev but it won't give me time needed. We could discuss this if I found time it will be very cool. Send mp on ha community forum.
